<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Features\AuthFeature\Query\" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="AutoMapper" Version="16.1.1" />
	  <PackageReference Include="FluentValidation" Version="11.11.0" />
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
	  <PackageReference Include="MediatR" Version="12.4.1" />
	  <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.10" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
	  <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
